accounts/urls.py
from django.urls import path
from .views import generateOTP, enter_otp, request_otp

app_name = "accounts"

urlpatterns = [
    path('get-otp/', generateOTP, name="get-otp"),
    path('request-otp/', request_otp, name='request-otp'),
    path('enter-otp/', enter_otp, name="enter-otp"),
]

bulkSMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sms.urls', namespace='sms')),
    path('accounts/', include('accounts.urls', namespace="accounts")),
]

sms/urls.py
from .views import *
from django.urls import path

app_name = "sms"

urlpatterns = [
    path('', Index, name="home"),
    path('send/', Send_Text, name='send'),
]

frontend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>RETECH BULK SMS</title>
</head>
<body>
    <div class="container">
        
        {% block body %}
            
        {% endblock body %}
            
    </div>
</body>
</html>

frontend/templates/enter-otp.html
{% extends 'base.html' %}


{% block body %}
    <form action="{% url 'accounts:enter-otp' %}" method="POST">{% csrf_token %}
        <input type="text" name="user-otp" id="" placeholder="Enter the digits">
        <button type="submit">Submit</button>
    </form>
{% endblock body %}
    

frontend/templates/enter-phone.html
{% extends 'base.html' %}



{% block body %}
    <form action="" method="POST">{% csrf_token %}
        <input type="text" name="phone-no" id="" placeholder="Enter a phone">
        <button type="submit">Submit</button>
    </form>
{% endblock body %}
    

frontend/templates/index.html
{% extends 'base.html' %}


{% block body %}
<form action="{% url 'sms:send' %}" method="post">{% csrf_token %}
    <textarea name="message" id="" cols="30" rows="10"></textarea>
    <button type="submit">Send</button>
</form>
{% endblock body %}
    